---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - src/.internal/**/*.json
      - *.test.js
  coverage:
    enabled: true
    exclude_paths:
      - src/.internal/**/*.json
      - *.test.js
      - *.md
  metric:
    enabled: true