language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
sudo: false
before_install: if [[ `npm -v` == 2* ]]; then npm i -g npm@3; fi
install:
  - npm install
  - npm install -g jest
script: npm run test-coverage