matrix:
  include:
    - language: "node_js"
        node_js:
          - "node"
          - "8"
          - "7"
          - "6"
        sudo: false
        install:
          - npm install
        script: npm run test
    - language: "node_js"
        node_js:
          - "node"
        sudo: false
        install:
          - npm install
        script: npm run test-coverage
notifications:
  email: false