language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
sudo: false
before_install: if [[ `npm -v` == 2* ]]; then npm i -g npm@3; fi
install:
  - npm install
script: npm run test
jobs:
  include:
    - stage: Coverage
      node_js: "node"
      sudo: false
      install:
        - npm install
      script: npm run test-coverage